# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\nsecure_lab\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x12ValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\"8\n\x0fUserPreferences\x12\x11\n\tfav_color\x18\x01 \x01(\t\x12\x12\n\nfav_number\x18\x02 \x01(\x05\"M\n\nUserReport\x12\x18\n\x10is_authenticated\x18\x01 \x01(\x08\x12\x11\n\tfav_color\x18\x02 \x01(\t\x12\x12\n\nfav_number\x18\x03 \x01(\x05\x32N\n\x0cOrchestrator\x12>\n\x12\x45xecuteAccessCheck\x12\x10.secure_lab.Name\x1a\x16.secure_lab.UserReport2M\n\tValidator\x12@\n\x0cValidateUser\x12\x10.secure_lab.Name\x1a\x1e.secure_lab.ValidationResponse2S\n\x12PreferencesService\x12=\n\x0cGetUserStats\x12\x10.secure_lab.Name\x1a\x1b.secure_lab.UserPreferencesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAME']._serialized_start=30
  _globals['_NAME']._serialized_end=50
  _globals['_VALIDATIONRESPONSE']._serialized_start=52
  _globals['_VALIDATIONRESPONSE']._serialized_end=90
  _globals['_USERPREFERENCES']._serialized_start=92
  _globals['_USERPREFERENCES']._serialized_end=148
  _globals['_USERREPORT']._serialized_start=150
  _globals['_USERREPORT']._serialized_end=227
  _globals['_ORCHESTRATOR']._serialized_start=229
  _globals['_ORCHESTRATOR']._serialized_end=307
  _globals['_VALIDATOR']._serialized_start=309
  _globals['_VALIDATOR']._serialized_end=386
  _globals['_PREFERENCESSERVICE']._serialized_start=388
  _globals['_PREFERENCESSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
