# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """define the service (the public facing server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAccessCheck = channel.unary_unary(
                '/secure_lab.Orchestrator/ExecuteAccessCheck',
                request_serializer=services__pb2.Name.SerializeToString,
                response_deserializer=services__pb2.UserReport.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """define the service (the public facing server)
    """

    def ExecuteAccessCheck(self, request, context):
        """define the function
        what it takes in
        what it spits out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAccessCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAccessCheck,
                    request_deserializer=services__pb2.Name.FromString,
                    response_serializer=services__pb2.UserReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secure_lab.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secure_lab.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """define the service (the public facing server)
    """

    @staticmethod
    def ExecuteAccessCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_lab.Orchestrator/ExecuteAccessCheck',
            services__pb2.Name.SerializeToString,
            services__pb2.UserReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ValidatorStub(object):
    """internal service #1 checks the name to see if its in database (private cloud)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateUser = channel.unary_unary(
                '/secure_lab.Validator/ValidateUser',
                request_serializer=services__pb2.Name.SerializeToString,
                response_deserializer=services__pb2.ValidationResponse.FromString,
                _registered_method=True)


class ValidatorServicer(object):
    """internal service #1 checks the name to see if its in database (private cloud)
    """

    def ValidateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUser,
                    request_deserializer=services__pb2.Name.FromString,
                    response_serializer=services__pb2.ValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secure_lab.Validator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secure_lab.Validator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Validator(object):
    """internal service #1 checks the name to see if its in database (private cloud)
    """

    @staticmethod
    def ValidateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_lab.Validator/ValidateUser',
            services__pb2.Name.SerializeToString,
            services__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PreferencesServiceStub(object):
    """internal service #2 stores the favorite color and number of the person (private cloud)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserStats = channel.unary_unary(
                '/secure_lab.PreferencesService/GetUserStats',
                request_serializer=services__pb2.Name.SerializeToString,
                response_deserializer=services__pb2.UserPreferences.FromString,
                _registered_method=True)


class PreferencesServiceServicer(object):
    """internal service #2 stores the favorite color and number of the person (private cloud)
    """

    def GetUserStats(self, request, context):
        """returns stats about a user such as favorite color and number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreferencesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStats,
                    request_deserializer=services__pb2.Name.FromString,
                    response_serializer=services__pb2.UserPreferences.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secure_lab.PreferencesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secure_lab.PreferencesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreferencesService(object):
    """internal service #2 stores the favorite color and number of the person (private cloud)
    """

    @staticmethod
    def GetUserStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_lab.PreferencesService/GetUserStats',
            services__pb2.Name.SerializeToString,
            services__pb2.UserPreferences.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
